sudo: required
services:
  - docker


before_install:
  - docker build -t miroslavstancic/docker-react -f Dockerfile.dev .

script:
  - docker run miroslavstancic/docker-react npm run test -- --coverage
